import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from 'next/font/google'
import { HeaderComponent } from "@/components/common/header";
import { FooterComponet } from "@/components/common/footer";

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "CognIA-IntelliLearn App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <HeaderComponent/>
        {children}
        <FooterComponet/>
      </body>
    </html>
  );
}
